### ISSUE TITLE
glados.pt GPU model

### ISSUE THREAD

**Issue by PeDro0210** [R2D2FISH/glados-tts#11]
I was trying to use a GPU for loading the model, but it didn't worked

**Comment by R2D2FISH** [comment]
glados.pt is an 8bit quantization of the original model, and only intended to be run on CPU. I found that the ForwardTacotron model was so fast that the GPU overhead actually made the thing run slower. I lost the original files for the model due to my laptop going kaboom when playing Valorant but I have a new version of the model that sounds much better. If you'd like to try running that you can add me on Discord or something. The new version has both Portal 1 and Portal 2 voices built in, with distinct cadences.

**Comment by PeDro0210** [comment]
Yea sure :D, what's your discord. Mine is pedro021

**Comment by R2D2FISH** [comment]
Mine is r2d2_fish

**Comment by PeDro0210** [comment]
Already send a request :D
